name = "techtrek-budget"
main = "src/worker.js"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "personal-budget-db"
database_id = "10f220d4-1c10-49e9-b63e-5d4cb08d599f"

[[routes]]
pattern = "techtrekgt.com/finance"
zone_name = "techtrekgt.com"

[[routes]]
pattern = "techtrekgt.com/finance/*"
zone_name = "techtrekgt.com"
