export const ERROR_CODES = {
  INVALID_CREDENTIALS:  'INVALID_CREDENTIALS',
  RESET_CODE_INVALID:   'RESET_CODE_INVALID',
  SESSION_EXPIRED:      'SESSION_EXPIRED',
  UNAUTHORIZED:         'UNAUTHORIZED',
  // REM-21: Distinct code for suspended accounts so frontend avoids misinterpreting as session expiration/login redirect
  ACCOUNT_SUSPENDED:    'ACCOUNT_SUSPENDED',
  FORBIDDEN:            'FORBIDDEN',
  CSRF_INVALID:         'CSRF_INVALID',
  RATE_LIMITED:         'RATE_LIMITED',
  VALIDATION_ERROR:     'VALIDATION_ERROR',
  NOT_FOUND:            'NOT_FOUND',
  CONFLICT:             'CONFLICT',
  SYNC_CONFLICT:        'SYNC_CONFLICT',
  SYNC_SUSPICIOUS:      'SYNC_SUSPICIOUS',
  SERVICE_UNAVAILABLE:  'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR:       'INTERNAL_ERROR',
};
